# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1'),
        ),
    ]
